CREATE TABLE USERS (
	ID SERIAL PRIMARY KEY,
	LOGIN VARCHAR(100) NOT NULL UNIQUE,
	EMAIL VARCHAR(255) NOT NULL UNIQUE,
	PASSWORD_HASH VARCHAR(255) NOT NULL,
	CREATED_AT TIMESTAMP NOT NULL DEFAULT NOW()
);

CREATE INDEX IDX_USERS_ID ON USERS (ID);

CREATE INDEX IDX_USERS_LOGIN ON USERS (LOGIN);

CREATE INDEX IDX_USERS_EMAIL ON USERS (EMAIL);

CREATE TABLE TAGS (
	ID SERIAL PRIMARY KEY,
	NAME VARCHAR(100) NOT NULL,
	COLOR_HEX CHAR(7) NOT NULL DEFAULT USER_ID INTEGER NOT NULL REFERENCES USERS (ID) ON DELETE CASCADE,
	CREATED_AT TIMESTAMP NOT NULL DEFAULT NOW(),
	CONSTRAINT UQ_TAGS_NAME_USER UNIQUE (NAME, USER_ID)
);

CREATE INDEX IDX_TAGS_USER_ID ON TAGS (USER_ID);

CREATE TABLE USER_TASKS (
	ID SERIAL PRIMARY KEY,
	TAG_ID INTEGER NOT NULL REFERENCES TAGS (ID) ON DELETE CASCADE,
	TITLE VARCHAR(500) NOT NULL,
	DESCRIPTION TEXT,
	PRIORITY VARCHAR(20) NOT NULL DEFAULT STATUS VARCHAR(20) NOT NULL DEFAULT DEADLINE TIMESTAMP NULL,
	COMPLETED_AT TIMESTAMP NULL,
	CREATED_AT TIMESTAMP NOT NULL DEFAULT NOW(),
	CONSTRAINT CHK_TASKS_PRIORITY CHECK (PRIORITY IN ('low', 'medium', 'high', 'critical')),
	CONSTRAINT CHK_TASKS_STATUS CHECK (STATUS IN ('active', 'completed', 'cancelled')),
	CONSTRAINT CHK_COMPLETED_AT CHECK (
		(
			STATUS = 'completed'
			AND COMPLETED_AT IS NOT NULL
		)
		OR (
			STATUS != 'completed'
			AND COMPLETED_AT IS NULL
		)
	)
);

CREATE INDEX IDX_TASKS_TAG_ID ON USER_TASKS (TAG_ID);

CREATE INDEX IDX_TASKS_STATUS ON USER_TASKS (STATUS);

CREATE INDEX IDX_TASKS_DEADLINE ON USER_TASKS (DEADLINE);