CREATE TABLE USERS (
	ID SERIAL PRIMARY KEY,
	LOGIN VARCHAR(100) NOT NULL UNIQUE,
	EMAIL VARCHAR(255) NOT NULL UNIQUE,
	PASSWORD_HASH VARCHAR(255) NOT NULL,
	CREATED_AT TIMESTAMP NOT NULL DEFAULT NOW()
);

CREATE INDEX IDX_USERS_ID ON USERS (ID);
CREATE INDEX IDX_USERS_LOGIN ON USERS (LOGIN);
CREATE INDEX IDX_USERS_EMAIL ON USERS (EMAIL);



CREATE TABLE TAGS (
	ID SERIAL PRIMARY KEY,
	NAME VARCHAR(100) NOT NULL,
	COLOR_HEX CHAR(7) NOT NULL DEFAULT '#6C757D',
	USER_ID INTEGER NOT NULL REFERENCES USERS (ID) ON DELETE CASCADE,
	CREATED_AT TIMESTAMP NOT NULL DEFAULT NOW(),
	CONSTRAINT UQ_TAGS_NAME_USER UNIQUE (NAME, USER_ID)
);

CREATE INDEX IDX_TAGS_USER_ID ON TAGS (USER_ID);



CREATE TABLE USER_TASKS (
	ID SERIAL PRIMARY KEY,
	TAG_ID INTEGER NOT NULL REFERENCES TAGS (ID) ON DELETE CASCADE,
	TITLE VARCHAR(500) NOT NULL,
	DESCRIPTION TEXT,
	PRIORITY VARCHAR(20) NOT NULL DEFAULT 'medium',
	STATUS VARCHAR(20) NOT NULL DEFAULT 'active',
	DEADLINE TIMESTAMP NULL,
	COMPLETED_AT TIMESTAMP NULL,
	CREATED_AT TIMESTAMP NOT NULL DEFAULT NOW(),
	CONSTRAINT CHK_TASKS_PRIORITY CHECK (PRIORITY IN ('low', 'medium', 'high', 'critical')),
	CONSTRAINT CHK_TASKS_STATUS CHECK (STATUS IN ('active', 'completed', 'cancelled')),
	CONSTRAINT CHK_COMPLETED_AT CHECK (
		(
			STATUS = 'completed'
			AND COMPLETED_AT IS NOT NULL
		)
		OR (
			STATUS != 'completed'
			AND COMPLETED_AT IS NULL
		)
	)
);

CREATE INDEX IDX_TASKS_TAG_ID ON USER_TASKS (TAG_ID);
CREATE INDEX IDX_TASKS_STATUS ON USER_TASKS (STATUS);
CREATE INDEX IDX_TASKS_DEADLINE ON USER_TASKS (DEADLINE);



CREATE TABLE TELEGRAM_BINDINGS (
	ID SERIAL PRIMARY KEY,
	USER_ID INTEGER NULL REFERENCES USERS (ID) ON DELETE CASCADE,
	TELEGRAM_CHAT_ID BIGINT NOT NULL UNIQUE,
	BIND_CODE VARCHAR(6) NULL UNIQUE,
	CREATED_AT TIMESTAMP NOT NULL DEFAULT NOW()
);

CREATE INDEX IDX_TELEGRAM_BINDINGS_USER_ID ON TELEGRAM_BINDINGS (USER_ID);
CREATE INDEX IDX_TELEGRAM_BINDINGS_CHAT_ID ON TELEGRAM_BINDINGS (TELEGRAM_CHAT_ID);
CREATE INDEX IDX_TELEGRAM_BINDINGS_CODE ON TELEGRAM_BINDINGS (BIND_CODE);



ALTER TABLE TELEGRAM_BINDINGS
ALTER COLUMN TELEGRAM_CHAT_ID
DROP NOT NULL;



ALTER TABLE TELEGRAM_BINDINGS
ALTER COLUMN BIND_CODE TYPE VARCHAR(64);



CREATE TABLE USER_TOKENS (
	ID SERIAL PRIMARY KEY,
	USER_ID INTEGER NOT NULL REFERENCES USERS (ID) ON DELETE CASCADE,
	TOKEN VARCHAR(128) NOT NULL UNIQUE,
	TOKEN_TYPE VARCHAR(20) NOT NULL,
	EXPIRES_AT TIMESTAMP NOT NULL,
	IS_USED BOOLEAN NOT NULL DEFAULT FALSE,
	CREATED_AT TIMESTAMP NOT NULL DEFAULT NOW(),
	CONSTRAINT CHK_USER_TOKENS_TYPE CHECK (TOKEN_TYPE IN ('email_confirm', 'password_reset'))
);

CREATE INDEX IDX_USER_TOKENS_TOKEN ON USER_TOKENS (TOKEN);
CREATE INDEX IDX_USER_TOKENS_USER_ID ON USER_TOKENS (USER_ID);



ALTER TABLE USERS
ADD COLUMN EMAIL_CONFIRMED BOOLEAN NOT NULL DEFAULT FALSE;